### ISSUE TITLE
Node running guides

### ISSUE THREAD

**Issue by damip** [massalabs/docs#254]
**TODO for initial node runners:**
- [ ] make sure everything is working if we follow the steps described in `docs/node/initial.mdx`
- [ ] proof-read everything

**TODO for normal node runners:**
- [ ] fill the TODOs on how to import saved wallets
- [ ] add node routability setup at node install phase. Insist that without routability, their node will be unstable through lack of connectivity
  - [ ] for routability, DO NOT FORGET TO SET THE IP ADDRESS IN THE CONFIG
  - [ ] tell how to check that it is defined (eg. I think the client tells you your IP address on top of get_info (?))
- [ ] check that all links work
- [ ] try to render and see how it looks
- [ ] add a last phase where you check the status of your node:
  - [ ] routability check using an external service like https://portchecker.co/
  - [ ] make sure the node staking address is the one in the initial rolls file
  - [ ] make sure your node is connected to peers
- [ ] make sure everything is working if we follow the steps described in `docs/node/initial.mdx`
- [ ] proof-read everything
