### ISSUE TITLE
Release ready - Meta

### ISSUE THREAD

**Issue by qdrn** [massalabs/docs#62]
Even if not perfect this doc will soon be better than the one that is available right now. To be ready to switch we need to do the following:

**General**:
- [x] Remove TODO and create corresponding issues
- [x] Remove links to dead pages (tutorial for instance)
- Finish Home pages of every sections:
  - [x] #83

**Build Section**:
- [x] #38 
- [x] #40 
- [x] Reference buildnet (network page)

**Tutorial section**:
- [x] #75
- [x] #46 

**Once everything else is done**:
- [x] #65

That's what I see for now. Maybe I'm missing things. Feel free to complete. There might be things overlapping with existing issues (feel free to link them here).

Let's target to have a first release ready version for the end of June and improve from there!

**Comment by SlnPons** [comment]
@qdrn we can close this issue, can't we?
